module Phronomy
  class Persistence
    interface _Participant[T]
      def new: (Storage::View view) -> T
    end

    class Transaction
      def initialize: (Persistence persistence, Storage::View view, ?parent: Transaction?) -> void
      def participate: [T, R] (persistence: Persistence, adapter: _Participant[T]) { (T) -> R } -> R
      def committed?: () -> bool
      def validate!: () -> bool
      def close!: () -> bool
      def confirm!: () -> bool
    end

    def atomic: [R] () { (Transaction) -> R } -> R
  end
end
