module Phronomy
  module LLMAdapter
    class Base
      def complete: (untyped chat, String? message, ?config: Hash[untyped, untyped]) -> untyped
      def stream: (untyped chat, String? message, ?config: Hash[untyped, untyped]) { (untyped chunk) -> void } -> untyped
    end

    class RubyLLM < Base
    end
  end
end
